(() => {
"use strict";
const S="evren-jeofizik-teklif-v1",L="evren-jeofizik-pdf-layout-v1";
const M={header:["Üst Başlık",1],logo:["Firma Logosu",0],title:["PDF Başlığı",1],customer:["Müşteri Kartı",1],project:["Proje Kartı",1],dates:["Tarih Kartı",1],pricing:["Fiyatlandırma Bölümü",1],table:["Hizmet Tablosu",1],totals:["Toplam Kutusu",1],workflow:["Çalışma Planı",1],images:["Proje Görselleri",1],terms:["Teklif Koşulları",1],note:["Ek Not",1],approval:["İmza / Onay",1],footer:["Alt Bilgi",1]};
let rk="",d=null,sel="header",z=.62,fit=true,rt=0,mt=0;
const q=(s,e=document)=>e.querySelector(s),qa=(s,e=document)=>[...e.querySelectorAll(s)],cl=(v,a,b)=>Math.min(b,Math.max(a,v));
const esc=(v="")=>String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function st(){return read(S,{settings:{},companies:[],quotes:[]})}
function path(){const r=(location.hash||"").startsWith("#/")?location.hash.slice(1):location.pathname;return r.replace(/\/$/,"")||"/"}
function id(){const p=path();if(p==="/quotes/new")return"new";return p.match(/^\/quotes\/([^/]+)\/edit$/)?.[1]||""}
function base(){
 const x=id(),s=st(),old=x!=="new"?s.quotes?.find(v=>v.id===x):null;
 if(old)return JSON.parse(JSON.stringify(old));
 const c=s.companies?.find(v=>v.isDefault)||s.companies?.[0]||{};
 return{id:"live",no:"",date:new Date().toISOString().slice(0,10),validUntil:"",companyId:c.id||"",customer:"",contact:"",phone:"",email:"",project:"",location:"",province:"",district:"",neighborhood:"",licenseNo:"",licenseOwner:"",items:[],description:"",notes:"",workflow:[],images:[]};
}
function draft(){const r=path();if(!d||rk!==r){d=base();rk=r}return d}
function cap(){
 const f=q("#quote-form"),x=draft();if(!f||!x)return;
 qa("[name]",f).forEach(e=>{if(e.type!=="file")x[e.name]=e.value});
 const fs=qa("[data-item-index][data-item-field]",f);if(fs.length){const a=[];fs.forEach(e=>{const i=+e.dataset.itemIndex,k=e.dataset.itemField,p=x.items?.[i]||{};a[i]||={...p};a[i][k]=["quantity","price","vat"].includes(k)?+(e.value||0):e.value});x.items=a.filter(Boolean)}
 const wf=qa("[data-workflow-index]",f);if(wf.length)x.workflow=wf.sort((a,b)=>+a.dataset.workflowIndex-+b.dataset.workflowIndex).map(e=>e.value);
 const im=qa(".image-upload-grid img",f).map(e=>e.src).filter(Boolean);if(im.length||q(".image-upload-grid",f))x.images=im;
}
function co(x){const s=st();return s.companies?.find(v=>v.id===x.companyId)||s.companies?.find(v=>v.isDefault)||s.companies?.[0]||{name:"Evren Jeofizik Hiz. ve Tek. Tic. Ltd. Şti.",subtitle:"JEOFİZİK - JEOLOJİ HİZMETLERİ",address:"Konya",website:"www.evrenjeofizik.com",logo:"/assets/evren-jeofizik-logo-embedded.svg"}}
function money(v){return`${new Intl.NumberFormat("tr-TR",{minimumFractionDigits:2,maximumFractionDigits:2}).format(+(v||0))} TL`}
function date(v){if(!v)return"—";const x=new Date(`${v}T12:00:00`);return isNaN(x)?v:new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"long",year:"numeric"}).format(x)}
function totals(x){let sub=0,vat=0;(x.items||[]).forEach(i=>{const b=+(i.quantity||0)*+(i.price||0);sub+=b;vat+=b*+(i.vat||0)/100});return{sub,vat,total:sub+vat}}
function logo(c){const i=c.logo?`<img src="${esc(c.logo)}" alt="Logo"/>`:esc((c.name||"EJ").split(/\s+/).slice(0,2).map(v=>v[0]).join(""));return`<div class="company-logo pdf-editable-block" data-pdf-block="logo">${i}</div>`}
function sheet(x){
 const c=co(x),t=totals(x),loc=x.location||[x.neighborhood,x.district,x.province].filter(Boolean).join(" / ")||"—",items=x.items?.length?x.items:[{name:"Hizmet kalemi girilmemiştir",unit:"—",quantity:0,price:0,vat:0}];
 let n=2;
 const wf=x.workflow?.length?`<section class="print-section pdf-editable-block" data-pdf-block="workflow"><div class="print-section-heading"><span>${String(n++).padStart(2,"0")}</span><div><h3>Çalışma Planı</h3><p>Projenin uygulanma ve teslim aşamaları</p></div></div><div class="print-workflow">${x.workflow.map((v,i)=>`<div class="print-workflow-step"><span>${String(i+1).padStart(2,"0")}</span><strong>${esc(v)}</strong></div>`).join("")}</div></section>`:"";
 const imgs=x.images?.length?`<section class="print-section pdf-editable-block" data-pdf-block="images"><div class="print-section-heading"><span>${String(n++).padStart(2,"0")}</span><div><h3>Proje Görselleri</h3><p>Çalışma alanı ve projeye ait ek görseller</p></div></div><div class="print-image-grid">${x.images.map((v,i)=>`<figure><img src="${esc(v)}" alt="Görsel ${i+1}"/><figcaption>Görsel ${i+1}</figcaption></figure>`).join("")}</div></section>`:"";
 const terms=x.description?`<section class="print-section print-terms pdf-editable-block" data-pdf-block="terms"><div class="print-section-heading"><span>${String(n++).padStart(2,"0")}</span><div><h3>Teklif Koşulları</h3><p>Geçerlilik, ödeme ve uygulama esasları</p></div></div><div class="print-copy">${esc(x.description)}</div></section>`:"";
 return`<article class="print-sheet live-pdf-sheet"><div class="print-accent-bar"></div>
 <header class="print-header pdf-editable-block" data-pdf-block="header"><div class="print-brand">${logo(c)}<div><span class="print-brand-kicker">JEOFİZİK · JEOLOJİ</span><h2>${esc(c.name||"Evren Jeofizik")}</h2><p>${esc(c.subtitle||"")}</p><p>${esc(c.address||"")}</p></div></div><div class="print-document pdf-editable-block" data-pdf-block="title"><span>TEKLİF DOSYASI</span><h1>FİYAT TEKLİFİ</h1><div class="print-quote-number">${esc(x.no||"YENİ TEKLİF")}</div></div></header>
 <section class="print-intro-grid"><div class="print-party-card pdf-editable-block" data-pdf-block="customer"><span class="print-card-label">TEKLİF SUNULAN</span><h3>${esc(x.customer||"Müşteri / Firma")}</h3>${x.contact?`<p><b>Yetkili</b>${esc(x.contact)}</p>`:""}${x.phone?`<p><b>Telefon</b>${esc(x.phone)}</p>`:""}${x.email?`<p><b>E-posta</b>${esc(x.email)}</p>`:""}</div><div class="print-project-card pdf-editable-block" data-pdf-block="project"><span class="print-card-label">PROJE / ÇALIŞMA</span><h3>${esc(x.project||"Jeofizik ve jeoloji hizmetleri")}</h3><p><b>Çalışma alanı</b>${esc(loc)}</p>${x.licenseNo?`<p><b>Ruhsat no</b>${esc(x.licenseNo)}</p>`:""}${x.licenseOwner?`<p><b>Ruhsat sahibi</b>${esc(x.licenseOwner)}</p>`:""}</div><div class="print-date-card pdf-editable-block" data-pdf-block="dates"><div><span>Teklif tarihi</span><strong>${esc(date(x.date))}</strong></div><div><span>Geçerlilik tarihi</span><strong>${esc(date(x.validUntil))}</strong></div><small>Fiyatlar belirtilen geçerlilik tarihine kadar geçerlidir.</small></div></section>
 <section class="print-section print-pricing-section pdf-editable-block" data-pdf-block="pricing"><div class="print-section-heading"><span>01</span><div><h3>Hizmet ve Fiyatlandırma</h3><p>Çalışma kapsamında sunulacak hizmet kalemleri</p></div></div><table class="print-table pdf-editable-block" data-pdf-block="table"><thead><tr><th>#</th><th>Hizmet Açıklaması</th><th>Birim</th><th>Miktar</th><th>Birim Fiyat</th><th>KDV</th><th>Tutar</th></tr></thead><tbody>${items.map((i,k)=>`<tr><td><span class="item-index">${String(k+1).padStart(2,"0")}</span></td><td><strong>${esc(i.name||"Hizmet")}</strong></td><td>${esc(i.unit||"—")}</td><td>${+(i.quantity||0)}</td><td class="numeric-cell">${money(i.price)}</td><td>%${+(i.vat||0)}</td><td class="numeric-cell"><strong>${money(+(i.quantity||0)*+(i.price||0))}</strong></td></tr>`).join("")}</tbody></table><div class="print-totals pdf-editable-block" data-pdf-block="totals"><div class="print-total-row"><span>Ara Toplam</span><strong>${money(t.sub)}</strong></div><div class="print-total-row"><span>KDV</span><strong>${money(t.vat)}</strong></div><div class="print-total-row grand"><span>GENEL TOPLAM</span><strong>${money(t.total)}</strong></div><small>KDV dahil toplam teklif bedelidir.</small></div></section>
 ${wf}${imgs}${terms}${x.notes?`<section class="print-section print-note pdf-editable-block" data-pdf-block="note"><span>Ek Not</span><p>${esc(x.notes)}</p></section>`:""}
 <section class="print-approval pdf-editable-block" data-pdf-block="approval"><div><span>TEKLİFİ HAZIRLAYAN</span><strong>${esc(c.name||"Evren Jeofizik")}</strong><p>Yetkili / Kaşe / İmza</p></div><div><span>MÜŞTERİ ONAYI</span><strong>${esc(x.customer||"Müşteri / Firma")}</strong><p>Ad Soyad / Kaşe / İmza</p></div></section>
 <footer class="print-footer pdf-editable-block" data-pdf-block="footer"><div><strong>${esc(c.footer||c.name||"Evren Jeofizik")}</strong><span>${esc(c.address||"")}</span></div><div class="print-contact-list">${[c.phone,c.email,c.website].filter(Boolean).map(v=>`<span>${esc(v)}</span>`).join("")}</div></footer></article>`;
}
function pane(ed){
 let p=q(":scope > .live-preview-pane",ed);if(p)return p;
 p=document.createElement("aside");p.className="live-preview-pane";p.innerHTML=`<div class="live-preview-toolbar"><div><span class="live-indicator"><i></i> CANLI PDF</span><small>Değişiklikler anında görünür</small></div><div class="live-preview-actions"><button class="live-tool-btn" data-live="fit">Sığdır</button><label class="live-zoom"><span data-z>%62</span><input type="range" min="35" max="100" value="62" data-live="zoom"></label><button class="live-tool-btn live-tool-primary" data-live="print">PDF / Yazdır</button></div></div><div class="live-preview-inspector"><div class="live-inspector-head"><div><span>Seçili PDF öğesi</span><strong data-lab>Üst Başlık</strong></div><button class="live-reset" data-live="reset">Sıfırla</button></div><div class="live-inspector-controls"><label><span>Boyut <b data-val="scale">100%</b></span><input type="range" min="70" max="140" data-ctl="scale"></label><label data-wrow><span>Genişlik <b data-val="width">100%</b></span><input type="range" min="60" max="100" data-ctl="width"></label><label><span>Alt boşluk <b data-val="spacing">0 px</b></span><input type="range" min="0" max="50" data-ctl="spacing"></label></div><small>PDF üzerinde bir bölüme tıklayın; ayarlar sadece o bölüme uygulanır.</small></div><div class="live-preview-canvas"><div class="live-preview-stage"></div></div>`;
 ed.appendChild(p);wire(p);return p;
}
function lay(){const x=read(L,{version:1,blocks:{}});x.blocks||={};return x}
function bs(k){const v=lay().blocks[k]||{};return{scale:cl(+(v.scale??100),70,140),width:cl(+(v.width??100),60,100),spacing:cl(+(v.spacing??0),0,50)}}
function save(k,v){const x=lay();x.blocks[k]={...bs(k),...v};write(L,x)}
function apply(e,k){const v=bs(k),f=v.scale/100;e.style.zoom=String(f);e.style.marginBottom=`${v.spacing/f}px`;if(M[k]?.[1]){e.style.width=`${v.width/f}%`;e.style.marginLeft=e.style.marginRight="auto";e.style.maxWidth="none"}}
function applyAll(s,edit=false){if(!s)return;qa("[data-pdf-block]",s).forEach(e=>{const k=e.dataset.pdfBlock;apply(e,k);if(edit){e.classList.toggle("live-selected-block",k===sel);e.title=`${M[k]?.[0]||k} · düzenlemek için tıklayın`}})}
function insp(p){if(!M[sel])sel="header";const v=bs(sel);q("[data-lab]",p).textContent=M[sel][0];["scale","width","spacing"].forEach(k=>{q(`[data-ctl="${k}"]`,p).value=v[k];q(`[data-val="${k}"]`,p).textContent=k==="spacing"?`${v[k]} px`:`${v[k]}%`});const dis=!M[sel][1];q("[data-wrow]",p).classList.toggle("is-disabled",dis);q('[data-ctl="width"]',p).disabled=dis}
function render(){
 clearTimeout(rt);rt=setTimeout(()=>{const ed=q(".editor-shell"),x=draft();if(!ed||!x)return;cap();const p=pane(ed),c=q(".live-preview-canvas",p),g=q(".live-preview-stage",p),sy=c.scrollTop,sx=c.scrollLeft;g.innerHTML=sheet(x);g.style.setProperty("--live-preview-zoom",z);applyAll(q(".live-pdf-sheet",g),true);insp(p);requestAnimationFrame(()=>{c.scrollTop=sy;c.scrollLeft=sx;if(fit)fitP(p)})},20)
}
function fitP(p=q(".live-preview-pane")){if(!p)return;const c=q(".live-preview-canvas",p),g=q(".live-preview-stage",p);if(!c||!g)return;z=cl((c.clientWidth-36)/990,.35,.92);g.style.setProperty("--live-preview-zoom",z);q('[data-live="zoom"]',p).value=Math.round(z*100);q("[data-z]",p).textContent=`%${Math.round(z*100)}`}
function wire(p){
 p.addEventListener("click",e=>{const a=e.target.closest("[data-live]")?.dataset.live;if(a==="fit"){fit=true;fitP(p);return}if(a==="print"){cap();const g=q(".live-preview-stage",p);g.innerHTML=sheet(d);applyAll(q(".live-pdf-sheet",g));document.body.classList.add("live-preview-printing");requestAnimationFrame(()=>print());return}if(a==="reset"){const x=lay();delete x.blocks[sel];write(L,x);render();real();return}const b=e.target.closest("[data-pdf-block]");if(b&&b.closest(".live-pdf-sheet")){sel=b.dataset.pdfBlock;qa(".live-selected-block",p).forEach(v=>v.classList.remove("live-selected-block"));b.classList.add("live-selected-block");insp(p);e.preventDefault()}});
 p.addEventListener("input",e=>{if(e.target.dataset.live==="zoom"){fit=false;z=+e.target.value/100;q(".live-preview-stage",p).style.setProperty("--live-preview-zoom",z);q("[data-z]",p).textContent=`%${e.target.value}`;return}const k=e.target.dataset.ctl;if(!k)return;save(sel,{[k]:+e.target.value});const b=q(`.live-pdf-sheet [data-pdf-block="${sel}"]`,p);if(b)apply(b,sel);q(`[data-val="${k}"]`,p).textContent=k==="spacing"?`${e.target.value} px`:`${e.target.value}%`;real()});
}
function real(){qa(".print-sheet:not(.live-pdf-sheet)").forEach(s=>{[[".print-header","header"],[".print-brand .company-logo","logo"],[".print-document","title"],[".print-party-card","customer"],[".print-project-card","project"],[".print-date-card","dates"],[".print-pricing-section","pricing"],[".print-pricing-section .print-table","table"],[".print-pricing-section .print-totals","totals"],[".print-workflow","workflow"],[".print-image-grid","images"],[".print-terms","terms"],[".print-note","note"],[".print-approval","approval"],[".print-footer","footer"]].forEach(([a,k])=>{let e=q(a,s);if(e){if(["workflow","images"].includes(k))e=e.closest(".print-section")||e;e.dataset.pdfBlock=k}});applyAll(s)})}
function mount(){clearTimeout(mt);mt=setTimeout(()=>{const ed=q(".editor-shell"),x=id();if(ed&&x){ed.classList.add("live-preview-enabled");draft();cap();pane(ed);render()}else{rk="";d=null}real()},10)}
const sync=()=>requestAnimationFrame(()=>{cap();render()});
document.addEventListener("input",e=>{if(e.target.closest("#quote-form"))sync()});
document.addEventListener("change",e=>{if(e.target.closest("#quote-form")){setTimeout(sync,0);setTimeout(sync,80)}});
document.addEventListener("click",e=>{if(e.target.closest(".editor-shell [data-action]")){setTimeout(mount,0);setTimeout(mount,80)}});
addEventListener("hashchange",mount);addEventListener("popstate",mount);addEventListener("resize",()=>{if(fit)fitP()});addEventListener("afterprint",()=>document.body.classList.remove("live-preview-printing"));
const app=q("#app");if(app)new MutationObserver(ms=>{const only=ms.every(m=>(m.target instanceof Element?m.target:m.target.parentElement)?.closest?.(".live-preview-pane"));if(!only)mount()}).observe(app,{childList:true,subtree:true});
mount();
})();